### ISSUE TITLE
Getting error when installing pylzham on MacOS

### ISSUE THREAD

**Issue by Red1860** [Galaxy1036/SC-Assets-Downloader-GUI#3]
hi, I am getting this error when installing lzham

Collecting pylzham
  Using cached pylzham-0.1.1.tar.gz (109 kB)
Building wheels for collected packages: pylzham
  Building wheel for pylzham (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sf/4yt8hgxj1n511np5gfncnqwc0000gn/T/pip-install-ja6cx5pn/pylzham/setup.py'"'"'; __file__='"'"'/private/var/folders/sf/4yt8hgxj1n511np5gfncnqwc0000gn/T/pip-install-ja6cx5pn/pylzham/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/sf/4yt8hgxj1n511np5gfncnqwc0000gn/T/pip-wheel-w_rrql9n
       cwd: /private/var/folders/sf/4yt8hgxj1n511np5gfncnqwc0000gn/T/pip-install-ja6cx5pn/pylzham/
  Complete output (99 lines):
  WARNING: '' not a valid package name; please use only .-separated package names in setup.py
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.8
  creating build/lib.macosx-10.9-x86_64-3.8/lzham
  copying src/lzham/decompress.py -> build/lib.macosx-10.9-x86_64-3.8/lzham
  copying src/lzham/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/lzham
  copying src/lzham/compress.py -> build/lib.macosx-10.9-x86_64-3.8/lzham
  running build_ext
  building '_lzham' extension
  creating build/temp.macosx-10.9-x86_64-3.8
  creating build/temp.macosx-10.9-x86_64-3.8/src
  creating build/temp.macosx-10.9-x86_64-3.8/src/lib
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c src/lzham_module.cpp -o build/temp.macosx-10.9-x86_64-3.8/src/lzham_module.o
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c src/lib/lzham_api.cpp -o build/temp.macosx-10.9-x86_64-3.8/src/lib/lzham_api.o
  In file included from src/lib/lzham_api.cpp:3:
  In file included from src/lib/lzham_core.h:259:
  src/lib/lzham_traits.h:132:15: error: expected unqualified-id
           if ( LZHAM_HAS_DESTRUCTOR(T) )
                ^
  src/lib/lzham_traits.h:82:64: note: expanded from macro 'LZHAM_HAS_DESTRUCTOR'
  #define LZHAM_HAS_DESTRUCTOR(T) ((!scalar_type<T>::cFlag) && (!LZHAM_IS_POD(T)))
                                                                 ^
  src/lib/lzham_traits.h:71:33: note: expanded from macro 'LZHAM_IS_POD'
     #define LZHAM_IS_POD(T) std::__is_pod<T>::__value
                                  ^
  In file included from src/lib/lzham_api.cpp:3:
  In file included from src/lib/lzham_core.h:263:
  src/lib/lzham_vector.h:56:14: error: expected unqualified-id
           if (LZHAM_IS_BITWISE_COPYABLE(T))
               ^
  src/lib/lzham_traits.h:78:98: note: expanded from macro 'LZHAM_IS_BITWISE_COPYABLE'
  #define LZHAM_IS_BITWISE_COPYABLE(T) ((scalar_type<T>::cFlag) || (bitwise_copyable<T>::cFlag) || LZHAM_IS_POD(T))
                                                                                                   ^
  src/lib/lzham_traits.h:71:33: note: expanded from macro 'LZHAM_IS_POD'
     #define LZHAM_IS_POD(T) std::__is_pod<T>::__value
                                  ^
  In file included from src/lib/lzham_api.cpp:3:
  In file included from src/lib/lzham_core.h:263:
  src/lib/lzham_vector.h:101:14: error: expected unqualified-id
           if (LZHAM_IS_BITWISE_COPYABLE(T))
               ^
  src/lib/lzham_traits.h:78:98: note: expanded from macro 'LZHAM_IS_BITWISE_COPYABLE'
  #define LZHAM_IS_BITWISE_COPYABLE(T) ((scalar_type<T>::cFlag) || (bitwise_copyable<T>::cFlag) || LZHAM_IS_POD(T))
                                                                                                   ^
  src/lib/lzham_traits.h:71:33: note: expanded from macro 'LZHAM_IS_POD'
     #define LZHAM_IS_POD(T) std::__is_pod<T>::__value
                                  ^
  In file included from src/lib/lzham_api.cpp:3:
  In file included from src/lib/lzham_core.h:263:
  src/lib/lzham_vector.h:257:17: error: expected unqualified-id
              if (LZHAM_IS_BITWISE_COPYABLE(T))
                  ^
  src/lib/lzham_traits.h:78:98: note: expanded from macro 'LZHAM_IS_BITWISE_COPYABLE'
  #define LZHAM_IS_BITWISE_COPYABLE(T) ((scalar_type<T>::cFlag) || (bitwise_copyable<T>::cFlag) || LZHAM_IS_POD(T))
                                                                                                   ^
  src/lib/lzham_traits.h:71:33: note: expanded from macro 'LZHAM_IS_POD'
     #define LZHAM_IS_POD(T) std::__is_pod<T>::__value
                                  ^
  In file included from src/lib/lzham_api.cpp:3:
  In file included from src/lib/lzham_core.h:263:
  src/lib/lzham_vector.h:274:14: error: expected unqualified-id
           if (LZHAM_IS_BITWISE_COPYABLE(T))
               ^
  src/lib/lzham_traits.h:78:98: note: expanded from macro 'LZHAM_IS_BITWISE_COPYABLE'
  #define LZHAM_IS_BITWISE_COPYABLE(T) ((scalar_type<T>::cFlag) || (bitwise_copyable<T>::cFlag) || LZHAM_IS_POD(T))
                                                                                                   ^
  src/lib/lzham_traits.h:71:33: note: expanded from macro 'LZHAM_IS_POD'
     #define LZHAM_IS_POD(T) std::__is_pod<T>::__value
                                  ^
  In file included from src/lib/lzham_api.cpp:3:
  In file included from src/lib/lzham_core.h:263:
  src/lib/lzham_vector.h:323:14: error: expected unqualified-id
           if (LZHAM_IS_BITWISE_COPYABLE(T))
               ^
  src/lib/lzham_traits.h:78:98: note: expanded from macro 'LZHAM_IS_BITWISE_COPYABLE'
  #define LZHAM_IS_BITWISE_COPYABLE(T) ((scalar_type<T>::cFlag) || (bitwise_copyable<T>::cFlag) || LZHAM_IS_POD(T))
                                                                                                   ^
  src/lib/lzham_traits.h:71:33: note: expanded from macro 'LZHAM_IS_POD'
     #define LZHAM_IS_POD(T) std::__is_pod<T>::__value
                                  ^
  In file included from src/lib/lzham_api.cpp:3:
  In file included from src/lib/lzham_core.h:263:
  src/lib/lzham_vector.h:573:14: error: expected unqualified-id
              (LZHAM_IS_BITWISE_MOVABLE(T) || (is_vector<T>::cFlag)) ? NULL : object_mover, nofail);
               ^
  src/lib/lzham_traits.h:80:38: note: expanded from macro 'LZHAM_IS_BITWISE_MOVABLE'
  #define LZHAM_IS_BITWISE_MOVABLE(T) (LZHAM_IS_BITWISE_COPYABLE(T) || (bitwise_movable<T>::cFlag))
                                       ^
  src/lib/lzham_traits.h:78:98: note: expanded from macro 'LZHAM_IS_BITWISE_COPYABLE'
  #define LZHAM_IS_BITWISE_COPYABLE(T) ((scalar_type<T>::cFlag) || (bitwise_copyable<T>::cFlag) || LZHAM_IS_POD(T))
                                                                                                   ^
  src/lib/lzham_traits.h:71:33: note: expanded from macro 'LZHAM_IS_POD'
     #define LZHAM_IS_POD(T) std::__is_pod<T>::__value
                                  ^
  7 errors generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pylzham

**Comment by Galaxy1036** [comment]
Hi, look like it's a known issue on mac,
You should try to clone the pylzham repo, apply the modifications as described here: https://github.com/richgel999/lzham_codec/issues/6#issuecomment-73115021 and finally manually install the package by running `setup.py`

EDIT: i fixed this issue in the following [commit](https://github.com/Galaxy1036/pylzham/commit/8257dada2474724f126445d8468931043c2ebac5)

**Comment by Red1860** [comment]
Thanks its working now!

**Comment by Red1860** [comment]
One more thing, do you know how to extract the files that don't have a tex_sc file for it? For eg 

scenery_clashy_constructs_dl_opt.sc

This one, it doesn't have a tex_sc file.

**Comment by Galaxy1036** [comment]
Yeah you can use this tool: https://github.com/Galaxy1036/Old-Sc-Dumper

**Comment by Red1860** [comment]
So I tried to download pylzham again but now its giving me a different error. It worked a month ago.
[pylzham error.txt](https://github.com/Galaxy1036/SC-Assets-Downloader-GUI/files/5889277/pylzham.error.txt)

**Comment by Red1860** [comment]
I think the issue might be macOS Catalina , last time I think I tried it on macOS Mojave

**Comment by Red1860** [comment]
Ok I was able to fix it by installing the latest version of python3 using home-brew as lited here.
https://github.com/giampaolo/psutil/issues/1842

**Comment by Red1860** [comment]
So i was able to extract png from that tool thanks! Is there a way to also extract all the sprites from the single png?
