### ISSUE TITLE
SC-Assets-Downloader-GUI not working

### ISSUE THREAD

**Issue by hiendo3d** [Galaxy1036/SC-Assets-Downloader-GUI#6]
maybe Supercell fixed something so SC-Assets-Downloader-GUI now cant run.
Can you check and fix it?

**Comment by Galaxy1036** [comment]
It is still working, what kind of error do you get ?

**Comment by hiendo3d** [comment]
> It is still working, what kind of error do you get ?
Thank you for replying. This is my issue.

https://user-images.githubusercontent.com/99595169/154981797-89bb58ad-6352-4a38-b756-31a4f0dcad0b.mp4

**Comment by Galaxy1036** [comment]
Should be fixed in the latest commit :)

**Comment by hiendo3d** [comment]
Nice! Thank you so much for your work.
